---
abstract: 'Automatically create test data for DBIx::Class'
author:
  - 'Gareth Harper (cpan@spansh.co.uk)'
build_requires:
  Test::DBIx::Class: '0.40'
  Test::Most: '0.33'
  Test::Pod::Coverage: '1.08'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-DBIx-Class-Factory
requires:
  DateTime::Event::Random: '0.03'
  Moose: '2.1'
  String::Random: '0.22'
version: '0.03'
